[[main]]
  identifier = "home"
  name = "Home"
  url = "/en/"
  weight = 1
[[main]]
  identifier = "about"
  name = "About"
  url = "/en/about/"
  weight = 2
[[main]]
  identifier = "services"
  name = "Services"
  url = "/en/services/"
  weight = 3
[[main]]
  identifier = "projects"
  name = "Projects"
  url = "/en/projects/"
  weight = 4
[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/en/contact/"
  weight = 5
